language: generic
sudo: required
script: './build.sh'
services:
  - docker
before_deploy: ./build.sh ci-git-setup
after_deploy: ./build.sh ci-git-push
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/jossemargt-resume.pdf
  skip_cleanup: true
  on:
    repo: jossemarGT/resume
    branch: master
