
---
# ==============================================================================
#                                 WEBSITE HEADER
# ==============================================================================
website_title:    'Jonnatan Jossemar Cordero'
website_tagline:  'Maker, Lead Software Engineer and DevOps Advocate'
# ==============================================================================
#                                  GITHUB LINKS
# ==============================================================================
github_username: jossemarGT
github_reponame: resume
# ==============================================================================
#                                   HTML META
# ==============================================================================
title: 'jossemarGT résumé'
lang:   en
date:   February 26, 2022
author:
  - Jonnatan Jossemar Cordero
description: 'jossemargt resume'
keywords:
  - resume
  - cv
  - curriculum
  - curriculum vitae
  - lead software engineer
  - devops
# ==============================================================================
#                        CUSTOM HTML TO INJECT IN HEADER
# ==============================================================================
header-includes: ''
# ******************************************************************************
# *                            INSERT BEFORE <body>                            *
# ******************************************************************************
include-before: ''
# ******************************************************************************
# *                            INSERT BEFORE </body>                           *
# ******************************************************************************
include-after: ''
# ------------------------------------------------------------------------------
...
