
---
# ==============================================================================
#                                 WEBSITE HEADER
# ==============================================================================
website_title:    'Jonnatan Jossemar Cordero'
website_tagline:  'Maker, Software Engineering Manager and DevOps Advocate'
# ==============================================================================
#                                  GITHUB LINKS
# ==============================================================================
github_username: jossemarGT
github_reponame: resume
# ==============================================================================
#                                   HTML META
# ==============================================================================
title: 'jossemarGT résumé'
lang:   en
date:   September 12, 2021
author:
  - Jonnatan Jossemar Cordero
description: 'jossemargt resume'
keywords:
  - resume
  - cv
  - software engineer
  - devops
# ==============================================================================
#                        CUSTOM HTML TO INJECT IN HEADER
# ==============================================================================
header-includes: ''
# ******************************************************************************
# *                            INSERT BEFORE <body>                            *
# ******************************************************************************
include-before: ''
# ******************************************************************************
# *                            INSERT BEFORE </body>                           *
# ******************************************************************************
include-after: ''
# ------------------------------------------------------------------------------
...
