
---
# ==============================================================================
#                                 WEBSITE HEADER
# ==============================================================================
website_title:    'Jossemar Cordero'
website_tagline:  'Technical Lead, Generalist and DevOps Advocate'
# ==============================================================================
#                                  GITHUB LINKS
# ==============================================================================
github_username: jossemarGT
github_reponame: resume
# ==============================================================================
#                                   HTML META
# ==============================================================================
title: 'jossemarGT résumé'
lang:   en
date:   January 21, 2025
author:
  - Jossemar Cordero
description: 'jossemargt resume'
keywords:
  - resume
  - cv
  - curriculum
  - lead software engineer
  - technical lead
  - devops
  - kubernetes
# ==============================================================================
#                        CUSTOM HTML TO INJECT IN HEADER
# ==============================================================================
header-includes: ''
# ******************************************************************************
# *                            INSERT BEFORE <body>                            *
# ******************************************************************************
include-before: ''
# ******************************************************************************
# *                            INSERT BEFORE </body>                           *
# ******************************************************************************
include-after: ''
# ------------------------------------------------------------------------------
...
