
---
# ==============================================================================
#                                 WEBSITE HEADER
# ==============================================================================
website_title:    'Jossemar Cordero'
website_tagline:  'Software engineer, maker and maddo scientisto'
# ==============================================================================
#                                  GITHUB LINKS
# ==============================================================================
github_username: jossemarGT
github_reponame: resume
# ==============================================================================
#                                   HTML META
# ==============================================================================
title: 'jossemarGT résumé'
lang:   en
date:   September 09, 2018
author:
  - Jossemar Cordero
description: 'jossemargt resume'
keywords:
  - resume
  - cv
  - software engineer
  - devops
  - developer
# ==============================================================================
#                        CUSTOM HTML TO INJECT IN HEADER
# ==============================================================================
header-includes: ''
# ******************************************************************************
# *                            INSERT BEFORE <body>                            *
# ******************************************************************************
include-before: ''
# ******************************************************************************
# *                            INSERT BEFORE </body>                           *
# ******************************************************************************
include-after: ''
# ------------------------------------------------------------------------------
...
