---
# .github/workflows/default.yml

name: Generate resume artifacts
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build artifacts
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project init
            project update
            do pdf
      - uses: actions/upload-artifact@v3
        with:
          name: resume-artifacts
          retention-days: 1
          path: |
            dist/**/*.pdf
            dist/**/*.html
  release:
    needs: build
    if:  ${{ contains(github.ref, 'master') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: resume-artifacts
          path: dist
      - name: Pre-Release
        run: |
          ./build.sh ci-setup
          cp dist/site/index.html docs/index.html
          ./build.sh ci-gh-page-bump
      - name: Publish PDF
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: true
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            dist/pdf/*.pdf
      - name: Plubish GH Pages
        run: |
          ./build.sh ci-gh-page-publish
